### ISSUE TITLE
[MacOS Catalina] Only works if run from terminal, asks for unnecessary permissions

### ISSUE THREAD

**Issue by DanielPower** [smolck/uivonim#72]
On MacOS Catalina, after copying to the Applications directory, the app can be successfully run using `open -a uivonim` in the terminal. 

If you try to launch the application by double clicking it in Finder, or through a launcher like Spotlight or Alfred, it will first ask for a bunch of permissions it shouldn't need, and then get stuck.

Here are the unnecessary permissions it requests:

- Contacts
- Calendars
- Reminders
- Photos

It also requests permission to accept incoming network connections.

And here is the state it gets stuck in:

![Screen Shot 2020-11-26 at 11 07 02 AM](https://user-images.githubusercontent.com/12166320/100363605-87ef1980-2fd7-11eb-92d3-5877fff84ec8.jpg)

In this state there is no cursor, and it will not respond to any form of input. You cannot type : to enter a command or open a file.

**Comment by clason** [comment]
The permissions are due to Uivonim looking in your home folder and traversing subfolders looking for files. (Including the folders where macOS stores the mentioned objects -- it's not accessing them directly!) I'll look into where this is done in the code and whether that can be made more targeted. Not sure where the network connections are coming from -- maybe Electron/Chromium? (I have not observed this behavior myself, though.)

The other issue is related to environment variables: If you start Uivonim from the command line, it inherits these from the terminal shell. If you do it from the Finder, these variables aren't set by default. In particular, these include `PATH` and the `LC_*` variables -- if the former doesn't contain where `neovim` is installed, you'll see exactly what you observe.

**Comment by clason** [comment]
Try adding
```bash
export PATH="/usr/local/bin:$PATH"
launchctl setenv PATH $PATH
```
to your `.bash_profile` and restarting (just the Dock with `osascript -e 'tell app "Dock" to quit'` is enough).

**Comment by smolck** [comment]
@DanielPower https://github.com/smolck/uivonim/commit/48fc9e25b7f118f67f3034ed8c42c25e28cfa287 should fix the problem with uivonim getting stuck/not loading (mostly; there appears to be a new issue where the UI doesn't fully appear until you press a character, although that might just be my end). 

As for the problem with asking for those random permissions, I don't appear to be experiencing this on Big Sur, so it may just be a Catalina thing (although I really don't know); regardless, you should be able to safely deny permission to those things. If not having those permissions does break the editor somehow though, then I'll have to look through the code to try and find out why.

**Comment by DanielPower** [comment]
I've since upgraded to Big Sur. Out of curiosity, I tested and the issue still occurred on the version of uivonim I had installed when posting this issue. Downloaded the latest release with your fix, and it did indeed resolve the issue. Looking forward to giving it a proper try. Thank you for the fix :)

**Comment by smolck** [comment]
@DanielPower No problem, thank you for opening the issue! And of course, if you come across any other bugs, problems, etc., feel free to open an issue or ask about it on Gitter, and I’ll do my best to help.
